version: "3.9"

services:
  nginx:
    build: ./srcs/requirements/nginx
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./wordpress:/usr/share/nginx/html
    depends_on:
      - wordpress
    networks:
      - inception

  wordpress:
    build: ./srcs/requirements/wordpress
    container_name: wordpress
    image: wordpress
    restart: always
    volumes:
      - wp_data:/var/www/html
      - db_data:/var/lib/mysql
    depends_on:
      - mariadb
    environment:
      - DB_HOST=mariadb
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - inception

  mariadb:
    build: ./srcs/requirements/mariadb
    container_name: mariadb
    image: mariadb
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ADMIN=${MYSQL_ADMIN}
      - MYSQL_ADMIN_PASSWORD=${MYSQL_ADMIN_PASSWORD}
    networks:
      - inception

volumes:
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hakaraou/data/wordpress
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hakaraou/data/mariadb
  wordpress_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hakaraou/data/wordpress
  wordpress_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hakaraou/data/mariadb

networks:
  inception:
    driver: bridge