services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb:user
    # healthcheck:
    #   test: ["CMD", "nc", "-zv", "mariadb", "3306"]
    #   interval: 1s
    #   timeout: 5s
    #   retries: 10
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MDB_ROOT_PASSWORD}
    volumes:
      - mariadb:/var/lib/mysql #??????????
    networks:
      - inception
    restart: always

volumes:
  mariadb:

networks:
  inception:
    name: inception