version: "3.5"

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_user_password:
    file: ../secrets/db_user_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  ftp_user_password:
    file: ../secrets/ftp_user_password.txt

services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb:hakaraou
    container_name: mariadb
    env_file:
      - .env
    secrets:
      - db_root_password
      - db_user_password
    networks:
      - wp-net
    volumes:
      - wp-database-vol:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  wordpress:
    depends_on:
      mariadb:
        condition: service_healthy
    build: ./requirements/wordpress
    image: wordpress:hakaraou
    container_name: wordpress
    env_file:
      - .env
    secrets:
      - wp_admin_password
      - db_user_password
      - wp_user_password
    networks:
      - wp-net
    volumes:
      - wp-websitef-vol:/var/www/html
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9000"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  nginx:
    depends_on:
      wordpress:
        condition: service_healthy
    build: ./requirements/nginx
    image: nginx:hakaraou
    container_name: nginx
    env_file:
      - .env
    ports:
      - target: 443
        published: 443
    networks:
      - wp-net
    volumes:
      - wp-websitef-vol:/var/www/html
    restart: always

#bonus
  redis:
    depends_on:
      - wordpress
    build: ./requirements/bonus/redis
    image: redis:hakaraou
    container_name: redis
    networks:
      - wp-net
    restart: always

  ftp:
    depends_on:
      - wordpress
    build: ./requirements/bonus/ftp
    image: ftp:hakaraou
    container_name: ftp
    env_file:
      - .env
    secrets:
      - ftp_user_password
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    networks:
      - wp-net
    volumes:
      - wp-websitef-vol:/var/www/html
    restart: always

  static_website:
    build: ./requirements/bonus/static_website
    image: static_website:hakaraou
    container_name: static_website
    env_file:
      - .env
    ports:
      - "8000:80"
    networks:
      - wp-net
    restart: always

  adminer:
    depends_on:
      mariadb:
        condition: service_healthy
    build: ./requirements/bonus/adminer
    image: adminer:hakaraou
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - wp-net
    restart: always

  partainer:
    build: ./requirements/bonus/partainer
    image: partainer:hakaraou
    container_name: partainer
    ports:
      - "1221:2112"
    networks:
      - wp-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
#bonus

networks:
  wp-net:
    name: wp-net
    driver: bridge

volumes:
  wp-database-vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/hakaraou/Desktop/data/wordpress_db
# /home/hakaraou/data/wordpress_db      /home/hakaraou/Desktop/data/wordpress_db
  wp-websitef-vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/hakaraou/Desktop/data/wordpress_wp
#/home/hakaraou/data/wordpress_wp        /home/hakaraou/Desktop/data/wordpress_wp
