version: "3.5"

services:
  mariadb:
    build: ./requirements/MariaDB
    #ask
    image: mariadb
    env_file:
      - .env
    command: /db-app/tools/db-set.sh
    ports:
      - target: 3306
        published: 3306
    networks:
      - wp-net
    volumes:
      - wp-database-vol:/var/lib/mysql
    restart: always

  wordpress:
    build: ./requirements/WordPress
    image: wordpress
    env_file:
      - .env
    command: /usr/wp-set.sh
    ports:
      - target: 9000
        published: 9000
    networks:
      - wp-net
    volumes:
      - wp-websitef-vol:/var/www/html
    restart: always

  nginx:
    build: ./requirements/NGINX
    image: nginx
    env_file:
      - .env
    command: [ "/usr/sbin/nginx", "-g", "daemon off;" ]
    ports:
      - target: 443
        published: 443
    networks:
      - wp-net
    volumes:
      - wp-websitef-vol:/var/www/html
    restart: always

networks:
  wp-net:

volumes:
  wp-database-vol:
  wp-websitef-vol:
